import { Geist, Geist_Mono, Outfit, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navigation/Navbar";
import { Toaster } from "sonner";
import CreateCampaignButton from "@/components/ui/CreateCampaignButton";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const sans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800']
})

export const metadata = {
  title: "Sphere Agency",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${outfit.className} ${sans.className} antialiased`}
      >
        {children}
        <Toaster richColors={true} position="top-center" />
        <CreateCampaignButton />
      </body>
    </html>
  );
}
